### ISSUE TITLE
关于WA2系列的字库处理

### ISSUE THREAD

**Issue by differentrain** [kid23/PC_Projects#1]
您好。我尝试做WA2 Special Contents的汉化，体取了脚本，虽然bnr文件的一些语法还没有搞清楚，但应该不影响汉化了……我目前遇到的问题是字体，因为没有汉化经验，所以完全不知道字体要怎么处理，似乎是用的图片当作字体，但却搞不清楚其中的编码逻辑。我擅自分析了一下汉化版的方案，发现其中的脚本采取了很奇怪的编码形式，所以我想请教这其中是否有什么规律。
另外我能否使用一些汉化的文本？

**Comment by xueyinhualuo** [comment]
@differentrain 大佬有做出来吗，期待。网上关于WA2的解包和封包技术相关的文章还是比较少，似乎从解包看字体是用的tga的图片。

**Comment by samuhoshi** [comment]
> 您好。我尝试做WA2 Special Contents的汉化，体取了脚本，虽然bnr文件的一些语法还没有搞清楚，但应该不影响汉化了……我目前遇到的问题是字体，因为没有汉化经验，所以完全不知道字体要怎么处理，似乎是用的图片当作字体，但却搞不清楚其中的编码逻辑。我擅自分析了一下汉化版的方案，发现其中的脚本采取了很奇怪的编码形式，所以我想请教这其中是否有什么规律。
> 另外我能否使用一些汉化的文本？

我也在做这个项目，其实我们可以合作一下。邮箱abc1507001046@qq.com
已经知道字体和编码的规律
还有请问您汉化成功了吗？

**Comment by differentrain** [comment]
> > 您好。我尝试做WA2 Special Contents的汉化，体取了脚本，虽然bnr文件的一些语法还没有搞清楚，但应该不影响汉化了……我目前遇到的问题是字体，因为没有汉化经验，所以完全不知道字体要怎么处理，似乎是用的图片当作字体，但却搞不清楚其中的编码逻辑。我擅自分析了一下汉化版的方案，发现其中的脚本采取了很奇怪的编码形式，所以我想请教这其中是否有什么规律。
> > 另外我能否使用一些汉化的文本？
> 
> 我也在做这个项目，其实我们可以合作一下。邮箱[abc1507001046@qq.com](mailto:abc1507001046@qq.com)
> 已经知道字体和编码的规律
> 还有请问您汉化成功了吗？

我放弃了。。。

**Comment by samuhoshi** [comment]
可否把ps3的汉化文本发我一下？提取太难了

**Comment by differentrain** [comment]
> 可否把ps3的汉化文本发我一下？提取太难了

PS3汉化文本是不存在的，我甚至还没开始汉化。我之前是想直接使用汉化组翻译的那些番外的文章文本。
至于提取，因为是很早的事所以项目早删了。
WA2资源包的格式结构我忘记是在哪看的，就记得是个国外的游戏翻译论坛，无非就是一些结构和Lzss算法压缩的。。。
